### ISSUE TITLE
./build.sh raspberrypi3 '2.15.1+rev2.dev' example_module failes with syntax error

### ISSUE THREAD

**Issue by ahsf** [resin-io-playground/kernel-module-build#7] opened 2018-10-11 11:11 UTC
I cloned the project, changed OS to '2.15.1+rev2.dev' and pushed it to a raspberrypi3 app.
Build fails with `scripts/basic/fixdep: 1: scripts/basic/fixdep: Syntax error: "(" unexpected`

```
git push resin master
...
[main]     Step 5/6 : RUN ./build.sh raspberrypi3 '2.15.1+rev2.dev' example_module
[main]      ---> Running in 9cb257de8946
[Info]     Still working...
[main]     Building images/raspberrypi3/2.15.1+rev2.dev/kernel_modules_headers.tar.gz...
[main]     --2018-10-11 10:59:02--  https://files.resin.io/images/raspberrypi3/2.15.1%2Brev2.dev/kernel_modules_headers.tar.gz
[main]     
[main]     Resolving files.resin.io (files.resin.io)... 
[main]     34.203.187.2, 52.72.241.228
[main]     Connecting to files.resin.io (files.resin.io)|34.203.187.2|:443... 
[main]     connected.
[main]     
[main]     HTTP request sent, awaiting response... 
[main]     200 OK
[main]     Length: 11448786 (11M) [application/gzip]
[main]     
[main]     Saving to: ‘kernel_modules_headers.tar.gz’
[main]     
...
[main]     
[main]     2018-10-11 10:59:02 (25.2 MB/s) - ‘kernel_modules_headers.tar.gz’ saved [11448786/11448786]
[main]     
[main]     make: Entering directory '/tmp/tmp.1k9FsmGYaq'
[main]       CC [M]  /usr/src/app/example_module_raspberrypi3_2.15.1+rev2.dev/hello.o
[main]     scripts/basic/fixdep: 1: scripts/basic/fixdep: Syntax error: "(" unexpected
[main]     
[main]     scripts/Makefile.build:334: recipe for target '/usr/src/app/example_module_raspberrypi3_2.15.1+rev2.dev/hello.o' failed
[main]     Makefile:1528: recipe for target '_module_/usr/src/app/example_module_raspberrypi3_2.15.1+rev2.dev' failed
[main]     make: Leaving directory '/tmp/tmp.1k9FsmGYaq'
[main]     make[1]: *** [/usr/src/app/example_module_raspberrypi3_2.15.1+rev2.dev/hello.o] Error 2
[main]     
[main]     make: *** [_module_/usr/src/app/example_module_raspberrypi3_2.15.1+rev2.dev] Error 2
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_f3nf)

**Comment by agherzan** [comment] 2018-10-11 18:54
Reproduced as it follows:
2.15.1+rev2 - fails indeed with the above error
2.13.6+rev1 - doesn't reproduce

So I suspect the kernel update introduced this issue. @floion will look into it.

**Comment by daghemo** [comment] 2018-10-17 17:57
Resin OS 2.13.6+rev1 and Resin OS 2.15.1+rev2 seems to use the same Linux kernel, that is 4.14.39.
So the following would work even on a Resin OS 2.15.1+rev2 devices as a workaround:

`RUN ./build.sh raspberrypi3 '2.13.6+rev1.dev' example_module
`

I've just tried it with a couple of real kernel modules that got broken while moving to 2.15.1.

I've also downloaded the kernel_modules_headers.tar.gz for both OS releases from https://files.resin.io/.
The first thing I noticed was:

```
-  /yocto/resin-board/build/tmp/work/raspberrypi3-poky-linux-gnueabi/kernel-modules-headers/1.0-r0/recipe-sysroot/usr/include/bits/stdlib.h \
+  /usr/include/x86_64-linux-gnu/bits/stdlib.h \
```

**Comment by ZubairLK** [comment] 2018-11-27 10:48
Looks like https://github.com/balena-os/meta-balena/commit/63baa421ada42aa6090e67e60324bd90ebbab873#diff-2fb8aa708944c3b37fe82e673a7a7742 causes it.
And the 'right' fix seems to be something like this : 
https://github.com/openembedded/openembedded-core/commit/148fd7a5bfea5d18952355a294e6d36ca82291d2 instead

**Comment by imrehg** [comment] 2018-11-27 11:03
@ZubairLK that was the assessment about the cause of the issue earlier as well indeed.
See https://www.flowdock.com/app/rulemotion/resin-devices/threads/LzAzsTCKnbK-R8y07qhncULcdEn and  https://forums.balena.io/t/missing-scripts-basic-fixdep-file-during-build/4330/19?u=imrehg

Glad that there's an alternative route that you linked to.
cc @agherzan

**Comment by floion** [comment] 2019-05-30 10:44
This should be fixed for later OS releases

**Closed as completed by floion** 2019-05-30 10:44 UTC
